// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0DQdS9QXx2XtUXlPQbM2-18FgPhj1sA',
    appId: '1:560724875652:web:5cd473a48a56cc6482a5d1',
    messagingSenderId: '560724875652',
    projectId: 'nursingquizapp6',
    authDomain: 'nursingquizapp6.firebaseapp.com',
    storageBucket: 'nursingquizapp6.appspot.com',
    measurementId: 'G-08Q9LDBGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0lxwbp2Ed7T0RMavuOBF6ve6tTV33cQ',
    appId: '1:560724875652:android:649bc7c6ab417b1a82a5d1',
    messagingSenderId: '560724875652',
    projectId: 'nursingquizapp6',
    storageBucket: 'nursingquizapp6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx9atLNSh_VvLjfSPxPMsRB_ivurs23Z4',
    appId: '1:560724875652:ios:7e48a5c85e97271282a5d1',
    messagingSenderId: '560724875652',
    projectId: 'nursingquizapp6',
    storageBucket: 'nursingquizapp6.appspot.com',
    iosBundleId: 'com.example.nursingQuizApp6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx9atLNSh_VvLjfSPxPMsRB_ivurs23Z4',
    appId: '1:560724875652:ios:7e48a5c85e97271282a5d1',
    messagingSenderId: '560724875652',
    projectId: 'nursingquizapp6',
    storageBucket: 'nursingquizapp6.appspot.com',
    iosBundleId: 'com.example.nursingQuizApp6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0DQdS9QXx2XtUXlPQbM2-18FgPhj1sA',
    appId: '1:560724875652:web:ff93f3220c7d969582a5d1',
    messagingSenderId: '560724875652',
    projectId: 'nursingquizapp6',
    authDomain: 'nursingquizapp6.firebaseapp.com',
    storageBucket: 'nursingquizapp6.appspot.com',
    measurementId: 'G-8RNE9V7ZR0',
  );
}
